### ISSUE TITLE
About thread blocking

### ISSUE THREAD

**Issue by rocrui** [Baekalfen/ICAP-avscan#10]
when run sendString(requestBuffer) code in the scanFile method,I find that the thread is blocking.But i add thread.sleep(50) ,it run normally.What caused it? the code or ICAP server?

**Comment by Baekalfen** [comment]
Where do you add the sleep, and which version are you using (C# or Java)?

The call should be blocking, as it will wait for the result to come back.

**Comment by rocrui** [comment]
I am using this java vsersion.
![image](https://user-images.githubusercontent.com/31843004/40291770-917e80d4-5cf9-11e8-8f37-5ce176dcd4ff.png)
I add the sleep on 157 line and 195 line and in ICAP.java  .When run the sendByte() method, this thread will be blocking , add the sleep ,it will be normal.Do I need improve this code or  update the configuration of ICAP server?

**Comment by Baekalfen** [comment]
When you say it is blocking, do you mean it completely stops, and doesn't return from the function?

To me, it sounds like a server issue. Adding a sleep statement shouldn't change anything in the Java code. Try to look at the log of your ICAP server. It might give some hints.

**Comment by Baekalfen** [comment]
Closing this for now. Please reopen, if needed.
