### ISSUE TITLE
Question: Why you get false on return code 200

### ISSUE THREAD

**Issue by AndreasRusjaev** [Baekalfen/ICAP-avscan#26]
Hello,
i have one question, why you in Java Client return false on return code 200 in the Line 176. The Snippets:
switch (status){
                    case 100: break; //Continue transfer
                    case 200: return false;
                    case 204: return true;
                    case 404: throw new ICAPException("404: ICAP Service not found");
                    default: throw new ICAPException("Server returned unknown status code:"+status);
                }

Thanks a lot

**Comment by Baekalfen** [comment]
It's a long time ago I wrote it, but it looks like it returns `true` if an issue has been detected and 200 if not.
