### ISSUE TITLE
ICAP TIMEOUT

### ISSUE THREAD

**Issue by CodigoCarmesi** [Baekalfen/ICAP-avscan#5]
*i don´t speak english*

Hi, first thanks for share it
but i can´t run this, i send a simple text but doesn´t occur until the **icap 408 error**.

![image](https://cloud.githubusercontent.com/assets/15971354/21369435/abc6de92-c6e5-11e6-97da-2f161cb264cf.png)

i attach wireshark captures.
![image](https://cloud.githubusercontent.com/assets/15971354/21369251/dba93142-c6e4-11e6-9012-4e5d1ac6462a.png)
![image](https://cloud.githubusercontent.com/assets/15971354/21369352/56307a06-c6e5-11e6-9889-fa940df862f0.png)
![image](https://cloud.githubusercontent.com/assets/15971354/21369375/6c37ee38-c6e5-11e6-8660-bf6b30c6a9c3.png)

Thanks !
Regars ;)

**Comment by Baekalfen** [comment]
Thanks for posting!

Which version did you try? Java or C#?

**Comment by CodigoCarmesi** [comment]
Java

**Comment by Baekalfen** [comment]
I have set up a C-ICAP server with the "echo" service, but I have not been able to replicate the error.

The server could be stuck somewhere. Have you looked at the server logs?

A wild guess might be to insert a line with "HTTP/1.0 200 OK\r\n" before the line with "Content-Length". The server you use, might be expecting a more "complete" HTTP header.

Just so you can see how it looks to me:
C-ICAP client
![screen shot 2016-12-21 at 21 02 07](https://cloud.githubusercontent.com/assets/5528170/21404932/d5a2413c-c7c3-11e6-8547-4cf27f87663a.png)

Java client
![screen shot 2016-12-21 at 21 24 25](https://cloud.githubusercontent.com/assets/5528170/21404938/e7b56d90-c7c3-11e6-88cf-5ac29c917b7d.png)

**Comment by CodigoCarmesi** [comment]
these ejecution(JAVA) are using exactly the same code shared in github? or u was  has to modify some lines of code?
And whats mind "User-Agent : IT-Kartellet ICAP Client/1.1"?

**Comment by Baekalfen** [comment]
I am running the exact code, which is on GitHub right now.

As you can see form the "User-Agent", I ran the C-ICAP client as a test.

The User-Agent is just an identifier to show what client version is connecting.

**Comment by CodigoCarmesi** [comment]
can you help me with a capture of java ejecution in wireshark?

thanks so much

**Comment by Baekalfen** [comment]
I'm not sure what you mean? You already have done that in your first post.

I don't know what you want me to send?

I don't see any way to proceed, without you looking at the ICAP server to see if it stops before answering back. Until proven otherwise, that is the only logical conclusion I can draw from the information you have shown.

**Comment by CodigoCarmesi** [comment]
I change the header and it work but it are not considers the file to scan.

![image](https://cloud.githubusercontent.com/assets/15971354/21456060/dde84d3c-c903-11e6-96d3-50d167617832.png)

And another curiosity is only work sending REQMOD ,but in the options, this return RESPMOD.

`String clientIP = "92.30.36.210";
            
            String httpRequest  = 
            		"GET http://"+ clientIP+"/"+"eicar.com.txt"+ " HTTP/1.1\r\n"
            		+"Host: icap.heal.check\r\n\r\n";
            
            String httpResponse = 
            		"HTTP/1.1 200 OK\r\n"
            		+"Transfer-Encoding: chunked\r\n\r\n";
            
            String icapRequest=
                    "REQMOD icap://"+serverIP+":"+port+"/"+icapService+" ICAP/"+VERSION+"\r\n"
                    +"Allow: 204\r\n"
                    +"Connection: close\r\n"
                    +"Host: "+serverIP+"\r\n"
            		+"Encapsulated: req-hdr=0"
            		+ ", res-hdr="+httpRequest.length()
            		+ ", res-body="+(httpRequest.length()+httpResponse.length())+"\r\n\r\n";
                    
            sendString(icapRequest+httpRequest+httpResponse);`

could guide me why the file is not consider ?

Thanks!

**Comment by Baekalfen** [comment]
I can't really tell if your data is malformed, but something seems wrong with the GET and "200 OK" lines. I think you should only have one of them.

Apart from that, it looks like you have "\r\n\r\n" right after "44" in the Wireshark dump. It should only be "\r\n".

**Comment by Baekalfen** [comment]
The request should look something like this instead:

```
REQMOD icap://.../RESPMOD ICAP/1.0
Allow: 204
Connection: close
Host: ...
Encapsulated: ...

GET http://.../eicar.com.txt HTTP/1.1
Host: icap.heal.check
Transfer-Encoding: chunked

44
X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
0; ioef
```

**Comment by CodigoCarmesi** [comment]
And now don´t recognize the test malware file.

![image](https://cloud.githubusercontent.com/assets/15971354/21506998/8c673f7e-cc53-11e6-9469-0936445a6a9a.png)

**Comment by CodigoCarmesi** [comment]
@Baekalfen Thanks so much for your time and help me patiently!
Finally i get a response from my icap server!


![image](https://cloud.githubusercontent.com/assets/15971354/21523182/8709fb2e-ccea-11e6-92db-a185df87e04a.png)

![image](https://cloud.githubusercontent.com/assets/15971354/21523162/60c3c760-ccea-11e6-88a7-c426ae365a8e.png)

have a nice day

**Comment by Baekalfen** [comment]
Great to hear!

Did you end up changing the code? If so, I would very much like to get a pull request with the improvements.

**Comment by CodigoCarmesi** [comment]
I will send a pull request,but keep in mind each ICAP server work different *apparently*.

Best Regards
