### ISSUE TITLE
having issue while scanning file greater than 2 mb

### ISSUE THREAD

**Issue by at199** [Baekalfen/ICAP-avscan#7]
```
while((offset < STD_RECIEVE_LENGTH) && ((n = in.read(buffer, offset, 1)) != -1)) { // first part is to secure against DOS
			offset += n;
			//log.info("inside while");
			if (offset>endofheader.length+13){ // 13 is the smallest possible message "ICAP/1.0 XXX "
				//log.info("offset  "+offset);
				byte[] lastBytes = Arrays.copyOfRange(buffer, offset-endofheader.length, offset);
				log.info("lastBytes"+lastBytes.length);
				if (Arrays.equals(endofheader,lastBytes)){
					return new String(buffer,0,offset, StandardCharsetsUTF8);
				}
			}
		}
		throw new ICAPException("Error in getHeader() method");
```
if condition not stisfied
**here i am getting last byte length 5 and it comes to exception block**

**Comment by at199** [comment]
small update this issue is only for image upload

**Comment by Baekalfen** [comment]
What server are you running against? And are you able to dump the whole communication in Wireshark (or the likes) and post it here?

**Comment by at199** [comment]
actually all setup i got from client and don't have access . i use the above(your) code on dam update .every thing working fine except uploading of image more than 2 mb, offset going to max standerd size ie 8192. Is  there any configuration that blocking then i can ask to client,

**Comment by Baekalfen** [comment]
My code doesn't intentionally differentiate between filetypes. You'll have to provide some more information on the problem, otherwise it's going to be impossible to locate a bug.

**Comment by at199** [comment]
yes you re right, it may be a configuration issue, i need to check will let you know when getting any if form infra team

**Comment by at199** [comment]
info

**Comment by at199** [comment]
i am sorry for the trouble, this was a configuration issue.
